### ISSUE TITLE
panic POSTing to /requests under load on minikube

### ISSUE THREAD

**Issue by jldec** [projectriff-archive/http-gateway#13]
hitting the http-gateway at about 100 reqs/s
running inside minikube (with single-node kafka broker)
logs attached.

[go-panic.txt](https://github.com/projectriff/http-gateway/files/1507809/go-panic.txt)

**Comment by jldec** [comment]
I can only reproduce this when POSTing requests to the gateway at `http://host:port/requests/votes.` When I post to `/messages/votes` the problem does not seem to occur.

Additional log attached
[go-panic-2.txt](https://github.com/projectriff/http-gateway/files/1507922/go-panic-2.txt)

**Comment by ericbottard** [comment]
This is very likely a problem with lack or wrong synchronization on the map that tracks `correlationId`s
