### ISSUE TITLE
gateway returns "200 OK" even if function invocation failed.

### ISSUE THREAD

**Issue by making** [projectriff-archive/http-gateway#22]
```
$ curl -v $gateway/requests/my-func -H "Content-Type: application/json" -d '{"a":"b"}'

> POST /requests/my-func HTTP/1.1
> Host: **************
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 9
> 
< HTTP/1.1 200 OK
< Content-Type: application/json;charset=UTF-8
< Date: Wed, 03 Jan 2018 13:29:13 GMT
< Content-Length: 403
< 

{"timestamp":1514986153738,"status":500,"error":"Internal Server Error","exception":"com.fasterxml.jackson.databind.JsonMappingException","message":"Can not construct instance of com.fasterxml.jackson.databind.JsonNode: abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information\n at [Source: [B@26e6eceb; line: 1, column: 1]","path":"/"}
```

I'm not sure if this is by design but it does not seem to be a good experience like following:

![image](https://user-images.githubusercontent.com/106908/34522493-36a8d8d8-f0d6-11e7-836a-862570287f16.png)

**Comment by ericbottard** [comment]
I agree with @markfisher that this goes beyond a mere gateway issue. Currently, functions have been considered on the happy path only. There is only one input and one output. We need to address exceptional conditions somehow (be it with a "context" parameter, or via support for multiple outputs, or making it the responsibility of the invoker — in a consistent way, as Mark said).

For now, there is nothing we can do at the GW level IMO

**Comment by markfisher** [comment]
we will begin exploring this in the 0.0.4 timeframe within the context of general error handling
