### ISSUE TITLE
Investigate slow performance of /requests vs /messages

### ISSUE THREAD

**Issue by ericbottard** [projectriff-archive/http-gateway#24]

**Comment by ericbottard** [comment]
Turns out the gateway itself is not particularly bad (eg when used with `square`) but it's in the context of the springone demo that I see contention. Can you confirm @markfisher @jldec and if so, could it be related to the use of the redis client?

**Comment by jldec** [comment]
I've been seeing pretty good numbers as well (with some variance)
OK to close this for now.
