### ISSUE TITLE
Drive optional Close method on Producer and Consumer interfaces

### ISSUE THREAD

**Issue by glyn** [projectriff-archive/http-gateway#32]
Currently, the gateway code is tightly bound to the Kafka transport. The gateway code drives the concrete `Close` method on `Producer` and `Consumer` instances. This will need to change when the transport is injected into the gateway as abstract `Producer` and `Consumer` instances.

The interfaces in the transport package should be documented to say that a method with signature `Close() error` may optionally be implemented by the underlying transport.

The gateway code should introspect the `Producer` and `Consumer` instances and, if `Close` is implemented, drive `Close` when the `Producer` and `Consumer` are finished with, respectively.

**Comment by glyn** [comment]
Example code:
```
if prod, ok := producer.(io.Closer); ok {
    defer prod.Close()
}
```

**Comment by ericbottard** [comment]
Done in 82a5b7a27e4f40fba144abc9c5a5b9b41cbac97d
